#!/usr/bin/python3
''' 
    """actorize as many numbers as possible into a product of two smaller numbers
    """
'''
from sys import argv, stderr

def main():
    '''
    """Factorize as many numbers as possible into a product of two smaller numbers.

    Returns:
        number: 0  
    """    
    '''
    if len(argv) != 2:
        print("there is no file to read",file=stderr)
        exit()

    try:
        the_file = open(argv[1], 'r')
    except FileNotFoundError:
        print("no file to read",file=stderr)
        exit()

    for line in the_file:
        try:
            num = int(line.strip())
            if num > 1:
                print("{}={}*{}".format(num, num, 1))
        except Exception:
            continue
    the_file.close()
    return 0

if __name__ == '__main__':
    main()
