#!/usr/bin/python3
''' 
    """actorize as many numbers as possible into a product of two smaller numbers
    """
'''
import sys


def main():
    '''
    """Factorize as many numbers as possible into a product of two smaller numbers.

    Returns:
        number: 0  
    """    
    '''

    try:
        with open(sys.argv[1], 'r') as file:
            for line in file:
                try:
                    num = abs(int(line))

                    if num > 1:
                        print(f"{num}={num}*1")
                except ValueError:
                    print(f"Invalid input: {line.strip()}")
    except FileNotFoundError:
        sys.exit(1)
    return 0

if __name__ == '__main__':
    if len(sys.argv) < 2:
        sys.exit(1)

    main()
